"""add pipelines and pipeline runs

Revision ID: b61d25c710d5
Revises: 08784c097e37
Create Date: 2026-07-16 16:17:56.382992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b61d25c710d5'
down_revision: Union[str, Sequence[str], None] = '08784c097e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('max_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('min_rows_processed', sa.Integer(), nullable=True),
    sa.Column('max_start_delay_seconds', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_duration_seconds IS NULL OR max_duration_seconds > 0', name='ck_pipelines_max_duration_positive'),
    sa.CheckConstraint('max_start_delay_seconds IS NULL OR max_start_delay_seconds >= 0', name='ck_pipelines_max_start_delay_nonnegative'),
    sa.CheckConstraint('min_rows_processed IS NULL OR min_rows_processed >= 0', name='ck_pipelines_min_rows_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_pipelines_name')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('external_run_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=True),
    sa.Column('quality_checks_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::JSONB"), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('logs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::JSONB"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('succeeded', 'failed', 'cancelled')", name='ck_pipeline_runs_status'),
    sa.CheckConstraint('completed_at >= started_at', name='ck_pipeline_runs_valid_time_range'),
    sa.CheckConstraint('quality_checks_failed >= 0', name='ck_pipeline_runs_quality_checks_nonnegative'),
    sa.CheckConstraint('rows_processed IS NULL OR rows_processed >= 0', name='ck_pipeline_runs_rows_nonnegative'),
    sa.ForeignKeyConstraint(
        ['pipeline_id'],
        ['pipelines.id'],
        name='fk_pipeline_runs_pipeline_id_pipelines',
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'external_run_id', name='uq_pipeline_runs_pipeline_external_run')
    )
    op.create_index('ix_pipeline_runs_completed_at', 'pipeline_runs', [sa.literal_column('completed_at ASC NULLS FIRST')], unique=False)
    op.create_index('ix_pipeline_runs_status', 'pipeline_runs', [sa.literal_column('status ASC NULLS FIRST')], unique=False)
    op.add_column('incidents', sa.Column('pipeline_run_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('uq_incidents_pipeline_run_id', 'incidents', ['pipeline_run_id'])
    op.create_foreign_key(
        'fk_incidents_pipeline_run_id_pipeline_runs',
        'incidents',
        'pipeline_runs',
        ['pipeline_run_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_incidents_pipeline_run_id_pipeline_runs',
        'incidents',
        type_='foreignkey',
    )
    op.drop_constraint('uq_incidents_pipeline_run_id', 'incidents', type_='unique')
    op.drop_column('incidents', 'pipeline_run_id')
    op.drop_index('ix_pipeline_runs_status', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_completed_at', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
