"""add incident memory and diagnoses

Revision ID: c25f84c7af1c
Revises: 98e2749e497a
Create Date: 2026-07-27 15:47:25.956101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = 'c25f84c7af1c'
down_revision: Union[str, Sequence[str], None] = '98e2749e497a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_diagnoses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('likely_causes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text_model_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_incident_diagnoses_confidence_range'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', name='uq_incident_diagnoses_incident_id')
    )
    op.create_table('incident_memories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('incident_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_input', sa.String(), nullable=False),
    sa.Column('embedding', VECTOR(dim=256), nullable=False),
    sa.Column('embedding_model_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', name='uq_incident_memories_incident_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_memories')
    op.drop_table('incident_diagnoses')
    # ### end Alembic commands ###
